### ISSUE TITLE
how to Install pyb on RaspberryPi. Please guide.

### ISSUE THREAD

**Issue by mchaudh4** [KipCrossing/Micropython-AD9833#1]
Hi , i am not able to install the pyb library. Because of this issue, i am not able to use the ad9833 ic. Please guide.

**Comment by KipCrossing** [comment]
Hi there,

The guide in the readme is for the [PyBoard](https://store.micropython.org/product/PYBv1.1H) and not the Raspberry Pi; hence why you can't `import pyb`. I suppose it could be used for the Raspberry Pi, but you'll need to setup spi and the ss pin yourself. You'll probably need to get python spi driver like [this one](https://pypi.org/project/spidev/), if you don't already have it and adjust the code to use the correct spi methods: ie.  `spi.xfer(to_send)` instead of `spi.send(to_send)`. 

Let me know how you go.

Kip
